[book]
authors = ["Yi-Wen Hung"]
language = "zh-TW"
multilingual = true
src = "src"
title = "Introduction to Programming (II)"
description = "程式設計(二)教材"

[output.html]
mathjax-support = true
edit-url-template = "https://github.com/stevenokm/i2p-nthu-math/edit/main/i2p2/{path}"